### ISSUE TITLE
Addressing the limitations

### ISSUE THREAD

**Issue by linusnorton** [capitainetrain/csa-challenge#31]
Do you have any guidance as to how to address any of the limitations? Specifically I'm looking to address:

`it computes the earliest arrival. However, a better solution might leaver later and arrive at the same time`

**Comment by espadrine** [comment]
This project is meant to remain simple. However, I believe it can be done by keeping track of overall travel duration, similarly to more classic pathfinding algorithms.

I am not sure whether the tests currently require not to have that bug fixed, but it is possible. This project is only for fun, to have a go at comparing language and implementation performance!

**Comment by linusnorton** [comment]
Yeah I was just wondering what the most peformant way of doing it would be. I thought about continually  replanning at later time periods until the original arrival time is no longer achievable or running an inverted version of the algorithm to find the latest departure that still arrives by the original arrival time.
