### ISSUE TITLE
Readability?

### ISSUE THREAD

**Issue by adericbourg** [capitainetrain/csa-challenge#5]
Does the code has really to be the the "most **un**readable" (see README)?

**Comment by Signez** [comment]
I don't think you understood what @Tristramg was trying to say, actually; but it may be missing an `either` somewhere. They are only propositions :wink: 

If you can provide a [Brainf*ck](https://en.wikipedia.org/wiki/Brainfuck) implementation of the CSA algorithm, it would be great!
