### ISSUE TITLE
Javascript is better

### ISSUE THREAD

**Issue by pietercolpaert** [capitainetrain/csa-challenge#9]
https://github.com/linkedconnections/csa.js

 ;-)

**Comment by Tristramg** [comment]
you were too lazy to re-implement it to work in the context of the challenge?

**Comment by pietercolpaert** [comment]
No: I will open a pull request later this year with the implementation :) Thought I should close this issue instead of leaving it open until then ;)

**Comment by pietercolpaert** [comment]
For the time being, you can now see this library in action from your browser: http://linkedconnections.org/
